FactoryBot.create(:template, text: "There is a %{model_name}", kind: :model)
FactoryBot.create(:template, text: "There is an %{model_name}", kind: :model)
FactoryBot.create(:template, text: "There is the %{model_name}", kind: :model)
FactoryBot.create(:template, text: "There is a %{model_name} model", kind: :model)
FactoryBot.create(:template, text: "There is an %{model_name} model", kind: :model)
FactoryBot.create(:template, text: "There is the %{model_name} model", kind: :model)

FactoryBot.create(:template, text: "The %{model_name} has a %{field_name}", kind: :field)
FactoryBot.create(:template, text: "The %{model_name} has an %{field_name}", kind: :field)
FactoryBot.create(:template, text: "The %{model_name} has the %{field_name}", kind: :field)
FactoryBot.create(:template, text: "The %{model_name} has a %{field_name} field", kind: :field)
FactoryBot.create(:template, text: "The %{model_name} has an %{field_name} field", kind: :field)
FactoryBot.create(:template, text: "The %{model_name} has the %{field_name} field", kind: :field)
FactoryBot.create(:template, text: "The %{model_name} has %{field_name}, %{field_name} fields", kind: :field)
FactoryBot.create(:template, text: "The %{model_name} has %{field_name} and %{field_name} fields", kind: :field)

FactoryBot.create(:template, text: "The %{field_name} field has %{type} type", kind: :field_type)
FactoryBot.create(:template, text: "The %{field_name} field has a %{type} type", kind: :field_type)
FactoryBot.create(:template, text: "The %{field_name} field has an %{type} type", kind: :field_type)
